name: TheCore
version: '1.0'
main: org.leux.TheCore
api-version: 1.19
commands:
  thecore:
    description: A simple description.
  discord:
    description: Discord link
  bc:
    description: broadcast